apps/users/urls.py
# -*- coding: utf-8 -*-
from django.urls import path

from users import views
from users.views import RegisterView, LoginView


app_name = 'users'


urlpatterns = [
    # 登录页
    path('login/', LoginView.as_view(), name='login'),
    # 注册页
    path('register/', RegisterView.as_view(), name='register'),
    # 退出登录
    path('logout/', views.user_logout, name='logout'),
]

king_blog/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from django.views.generic import TemplateView
from django.conf.urls import url, include
import xadmin
from django.conf.urls.static import static

from king_blog import settings


urlpatterns = [
    # 后台管理url
    path('xadmin/', xadmin.site.urls),
    # 后台富文本编辑器路由
    path('ckeditor', include('ckeditor_uploader.urls')),
    # 主页面
    url('^$', TemplateView.as_view(template_name='home/index.html'), name='home'),
    # app用户模块
    url(r'', include('users.urls', namespace='user')),
    # app博客管理
    url(r'^king/', include('blog.urls', namespace='blog')),
    # 验证码
    url(r'^captcha/', include('captcha.urls')),
]
# 富文本编辑配置
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class UserProfile(AbstractUser):
    """用户基本信息表"""
    author = models.CharField(max_length=60, verbose_name=u'昵称', default="")  # 跟文章作者关联
    nick_name = models.CharField(max_length=60, verbose_name=u'昵称', default="")
    birthday = models.DateField(verbose_name=u'生日', null=True, blank=True)
    gender = models.CharField(choices=(('male', u'男'), ('female', u'女')), max_length=8, default=u'')
    address = models.CharField(max_length=200, verbose_name=u'地址', default=u'')
    mobile = models.CharField(max_length=11, null=True, blank=True, verbose_name=u'手机号')
    image = models.ImageField(upload_to='images/%Y/%m', default=u'image/default.png', max_length=150, verbose_name=u'头像')

    class Meta:
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name
        # 表名，一般不修改
        db_table = 'user_info'

    def __str__(self):
        return self.username

apps/users/forms.py
# -*- coding: utf-8 -*-
import re

from django import forms
from captcha.fields import CaptchaField
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from users.models import UserProfile


# 自定义验证规则
def mobile_validate(value):
    mobile_re = re.compile(r'^(13[0-9]|15[012356789]|17[678]|18[0-9]|14[57]|19[0-9])[0-9]{8}$')
    if not mobile_re.match(value):
        raise ValidationError('手机号码格式错误')


class LoginForm(forms.Form):
    """
    登录验证
    """
    # initial 初始默认值
    username = forms.CharField(required=True, min_length=6, max_length=16, label='用户名')
    password = forms.CharField(required=True, min_length=6, widget=forms.widgets.PasswordInput, label='密码')


class RegisterForm(forms.Form):
    """
    注册验证表单
    """
    username = forms.CharField(required=True, min_length=6, max_length=16, label='用户名', error_messages={'required': "用户名6-16位，必须字母开头"})
    email = forms.EmailField(required=True, min_length=6, max_length=32, label='邮箱', error_messages={'required': "必须填写邮箱"})
    mobile = forms.CharField(required=True, max_length=11, label='手机号', error_messages={'required': "必须填写手机号，最大长度11位"})
    password = forms.CharField(required=True, min_length=6, max_length=16, widget=forms.widgets.PasswordInput, label='密码', error_messages={'required': '密码不能为空', 'min_length': '密码小于6', 'max_length': '密码大于12'})
    repassword = forms.CharField(required=True, min_length=6, max_length=32, widget=forms.widgets.PasswordInput, label='重复密码', error_messages={'required': '密码不能为空', 'min_length': '密码小于6', 'max_length': '密码大于12'})
    captcha = CaptchaField(required=True, error_messages={'invalid': '验证码错误'}, label='验证码')

    # def clean_username(self):
    #     """
    #     用户名校验规则
    #     """
    #     username = self.cleaned_data.get('username', '')
    #     result = re.match(r'[a-zA-Z]\w{5,}', username)
    #     if not result:
    #         raise ValidationError('用户名必须字母开头')
    #     return username


# class RegisterForm(ModelForm):
#     """
#     注册表单验证
#     """
#     # widget 密码不显示，label页面显示的文字
#     repassword = forms.CharField(required=True, min_length=6, max_length=32, error_messages={'required': "必须填写确认密码"}, label='确认密码', widget=forms.widgets.PasswordInput)
#
#     class Meta:
#         # 关联的数据库模型
#         model = UserProfile
#         # 自定义页面显示字段
#         fields = ['username', 'email', 'mobile', 'password']
#         # # 显示所有字段
#         # fields = "__all__"
#         # # 需要排除，不显示的字段
#         # exclude = ['first_name', 'last_name']

apps/users/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth.backends import ModelBackend
from django.contrib.auth.hashers import make_password
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout

from django.views.generic import View

from users.forms import LoginForm, RegisterForm
from users.models import UserProfile


# 重写认证
class CustomBackends(ModelBackend):
    """
    用户认证
    """
    def authenticate(self, request, username=None, password=None, **kwargs):
        try:
            # 可以同时使用username，email，mobile登录
            user = UserProfile.objects.get(Q(username=username)|Q(email=username)|Q(mobile=username))
            if user.check_password(password):
                return user
        except Exception as e:
            return None


# 用户登录
class LoginView(View):
    """
    用户登录模块，只处理get跟post请求
    """

    def get(self, request):
        """
        自动调用get请求
        """
        login_form = LoginForm()
        return render(request, 'user/login.html', context={'login_form': login_form})

    def post(self, request):
        """
        自动调用post
        """
        login_form = LoginForm(request.POST)
        # 检验是否验证成功，不成功会有errors信息
        if login_form.is_valid():
            # 需要跟html页面里面得form表单中的name相对应，html定义的是username就获取username
            user_name = login_form.cleaned_data.get('username', '')
            pass_word = login_form.cleaned_data.get('password', '')
            user = authenticate(username=user_name, password=pass_word)
            if user is not None and user.is_active:
                # 判断用户名密码是否有效
                login(request, user)
                return redirect('home')
            else:
                return render(request, 'user/login.html', locals())
        else:
            login_form = LoginForm()
            return render(request, 'user/login.html', locals())


# 用户注册
class RegisterView(View):
    """
    用户注册模块，只处理get跟post请求
    """
    def get(self, request):
        register_form = RegisterForm()
        return render(request, 'user/register.html', context={'register_form': register_form})

    def post(self, request):
        # 接收前端表单填写的数据
        register_form = RegisterForm(request.POST)
        # 数据校验，返回布尔
        if register_form.is_valid():
            username = register_form.cleaned_data.get('username', '')
            filter_result = UserProfile.objects.filter(username=username)
            if len(filter_result) > 0:
                return render(request, 'user/register.html', context={'error': '用户名已存在'})
            else:
                email = register_form.cleaned_data.get('email', '')
                mobile = register_form.cleaned_data.get('mobile', '')
                password1 = register_form.cleaned_data.get('password1', '')
                password2 = register_form.cleaned_data.get('password2', '')
                errors = []
                if (password2 != password1):
                    errors.append("两次输入的密码不一致!")
                    return render(request, 'user/register.html', context={'error': errors})
                password2 = password1
                user_profile = UserProfile()
                user_profile.username = username
                user_profile.email = email
                user_profile.mobile = mobile
                # 加密后的密码保存到数据库
                user_profile.password = make_password(password2)
                # 校验成功保存到数据库
                user_profile.save()
                # 注册成功跳转到登录页面
                return redirect('users:login')
        else:
            register_form = RegisterForm()
            # Python的内建函数locals()。它返回的字典对所有局部变量的名称与值进行映射
            return render(request, 'user/register.html', locals())


# 用户注销
def user_logout(request):
    logout(request)
    return redirect('home')

templates/user/login.html
{% extends 'home/base.html' %}
{% load staticfiles %}
 <!-- 登录样式 -->
{% block custom_css %}
    <link href="{% static 'css/login.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<form class="form-signin" action="{% url 'user:login' %}" method="post">
    <h2 class="form-signin-heading" style="text-align:center;">用户登录</h2>
    <div class="form-group marb20">
        {{ login_form.username.label_tag }}
        {{ login_form.username }}
    </div>
    <div class="form-group marb18">
        {{ login_form.password.label_tag }}
        {{ login_form.password }}
    </div>
    <label class="checkbox"><input type="checkbox" value="remember-me">记住密码</label>
    <button class="btn btn-large btn-primary" type="submit">登录</button><br><br>
    <p class="Small">
        <a href="{% url 'user:register' %}">新用户注册</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <a id="lnkHome" href="{% url 'home' %}">返回首页</a>
    </p>
    {% csrf_token %}
</form>
{% endblock %}

templates/user/register.html
{% extends 'home/base.html' %}

{% load staticfiles %}
 <!-- 注册样式 -->
{% block custom_css %}
    <link href="{% static 'css/register.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<form class="form-signin" action="{% url 'user:register' %}" method="post">
    <h2 class="form-signin-heading text-center" style="text-align:center;">注册账号</h2>

    {% if register_form.captcha.errors %}
        <div class="alert alert-warning">{{ register_form.captcha.errors }}</div>
    {% elif message %}
        <div class="alert alert-warning">{{ error }}</div>
    {% endif %}

    <div class="form-group marb20">
        {{ register_form.username.label_tag }}
        {{ register_form.username}}

    </div>

    <div class="form-group marb20"><br>
        {{ register_form.email.label_tag }}
        {{ register_form.email }}
    </div>

    <div class="form-group marb18">
        {{ register_form.mobile.label_tag }}
        {{ register_form.mobile }}
    </div>

    <div class="form-group marb18">
        {{ register_form.password.label_tag }}
        {{ register_form.password }}
    </div>
    <div class="form-group marb18">
        {{ register_form.repassword.label_tag }}
        {{ register_form.repassword }}
    </div>
    <div class="form-group marb18">
        {{ register_form.captcha.errors }}
        {{ register_form.captcha.label_tag }}
        {{ register_form.captcha }}
    </div>

    <button class="btn btn-large btn-primary" type="submit">注册</button><br><br>
    <p class="Small">
        <a href="{% url 'user:login' %}">用户登录</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <a id="lnkHome" href="{% url 'home' %}">返回首页</a>
    </p>
    {% csrf_token %}
</form>
<script>
$(function() {
    // Add refresh button after field (this can be done in the template as well)
    $('div.form-group img.captcha').after(
            $('<span style="float:right;" class="btn btn-info"><a href="#void" class="captcha-refresh" style="color:#fff;">换个验证码</a></span>')
            );

    $('.captcha-refresh').click(function(){
        var $form = $(this).parents('form');
        var url = location.protocol + "//" + window.location.hostname + ":"
                  + location.port + "/captcha/refresh/";

        // Make the AJAX-call
        $.getJSON(url, {}, function(json) {
            $form.find('input[name="captcha_0"]').val(json.key);
            $form.find('img.captcha').attr('src', json.image_url);
        });

        return false;
    });
});
</script>
{% endblock %}